#! /bin/bash -e

# NOTE: should be invoked as either:
#    ./msys-build-bash bash-VER.tar.gz
#    which will unpack the "pristine" source distribution, bash it, 
#    and begin the build,
# OR, as
#    ../msys-build-bash
#    where the current working directory is the unpacked and bashed
#    source distribution.
#
# bash is built without NLS support, because the 3.1 distribution
# does not provide any translations, so there's no point.

### hardcode PKG and tarball 
export PKG=bash
export VER=3.1.23
export BLD=2
export SYS=msys
_sysver=$(uname -r)
export SYSVER=${_sysver%%\(*}
VERMAJOR=${VER%%.*}
VERPATCH=${VER##*.}
VERMINOR=${VER%.*}
VERMINOR=${VERMINOR##*.}
FULLPKG=${PKG}-${VER}-${BLD}-${SYS} # not sysver
SRCDIR_=${PKG}-${VERMAJOR}.${VERMINOR}
RELDOCDIR=share/doc/${PKG}/${VER}
BINPKG=${PKG}-${VER}-${BLD}-${SYS}-${SYSVER}-bin.tar.xz
LICPKG=${PKG}-${VER}-${BLD}-${SYS}-${SYSVER}-lic.tar.xz
DOCPKG=${PKG}-${VER}-${BLD}-${SYS}-${SYSVER}-doc.tar.xz
SRCPKG=${PKG}-${VER}-${BLD}-${SYS}-${SYSVER}-src.tar.xz
BIN_CONTENTS="bin"
LIC_CONTENTS="${RELDOCDIR}/COPYING"
DOC_CONTENTS="--exclude ${RELDOCDIR}/COPYING
	share/doc share/info share/man/man1"

# displays error message and exits
error() {
        case $? in
                0) local errorcode=1 ;;
                *) local errorcode=$? ;;
        esac

        echo -e "\e[1;31m*** ERROR:\e[0;0m ${1:-no error message provided}";
        exit ${errorcode};
}

# displays information message
inform() {
        echo -e "\e[1;32m*** Info:\e[0;0m ${1}";
}

# displays warning message only
warning() {
        echo -e "\e[1;33m*** Warning:\e[0;0m ${1}";
}

# query
query() {
	while true
	do
          echo -e "\e[1;35m*** Query:\e[0;0m ${1}";
	  if read -e answer
	  then
	    query_result=$answer
	    return 0
	  else
	    # user did a ^D
	    echo -e "Quitting.\n"
	    exit 1
	  fi
	done
}

# displays command to stdout before execution
verbose() {
        echo "${@}"
        "${@}"
        return $?
}
export -f verbose warning inform error

cmparg=
set_cmparg() {
        case "$1" in
        *tar.bz2       ) cmparg="j" ;;
        *tar.lzma      ) cmparg=" --lzma" ;;
        *tar.xz        ) cmparg="J" ;;
        *tar.gz | *tgz ) cmparg="z" ;;
        *              ) cmparg="" ;;
        esac
}

specific_patchlevel=
do_patch() {
  #local patchfile_name;
  #local patchfile_path;
  #local patchlevel;
  if [ -n "$specific_patchlevel" ]
  then
    starting_patchlevel=$specific_patchlevel
    stopping_patchlevel=$specific_patchlevel
  else
    starting_patchlevel=0
    stopping_patchlevel=3
  fi
  specific_patchlevel=

  for patchfile_path
  do
    patchfile_name="${patchfile_path##*/}"

    if [ ! -e ${patchfile_path} ]
    then
      warning "patch ${patchfile_name} not found";
      continue;
    fi

    patchlevel=$starting_patchlevel

    while test $patchlevel -le $stopping_patchlevel
    do
      if patch -N -s --dry-run -p${patchlevel} -i ${patchfile_path} &> /dev/null
      then
        echo "*** applying patch ${patchfile_name}:";
        patch -N -p${patchlevel} -i ${patchfile_path} || error "patch ${patchfile_name} failed"
        break;
      elif patch -N -s --binary --dry-run -p${patchlevel} -i ${patchfile_path} &> /dev/null
      then
        echo "*** applying patch ${patchfile_name}:";
        patch -N --binary -p${patchlevel} -i ${patchfile_path} || error "patch ${patchfile_name} failed"
        break;
      elif patch -R -s --dry-run -p${patchlevel} -i ${patchfile_path} &> /dev/null
      then
        warning "patch ${patchfile_name} already applied; skipping";
        break;
      else
        if (( patchlevel == 3 ))
        then
          error patch "patch ${patchfile_name} will not apply";
        else
          patchlevel=`expr $patchlevel + 1`;
          continue;
        fi
      fi
    done
  done
}
export -f do_patch


if [ "x" != "x$1" ]; then
  if [ -d "$1" ]; then
    savedir="$PWD"
    cd "$1"
    srcdir="$PWD"
  elif [ -f "$1" ]; then
    case "$1" in
    *.tar.bz2 ) srcdir=`echo $1 | sed -e 's/\.tar\.bz2$//'`
                unpack=tbz
                savedir="$PWD" ;;
    *.tar.gz  ) srcdir=`echo $1 | sed -e 's/\.tar\.gz$//'`
                unpack=tgz
                savedir="$PWD" ;;
    *.zip     ) srcdir=`echo $1 | sed -e 's/\.zip$//'`
                unpack=zip
                savedir="$PWD" ;;
    *.tar.lzma ) srcdir=`echo $1 | sed -e 's/\.tar\.lzma$//'`
                unpack=tlz
                savedir="$PWD" ;;
    *.tar.xz )  srcdir=`echo $1 | sed -e 's/\.tar\.xz$//'`
                unpack=txz
                savedir="$PWD" ;;
    * ) error "Bad src directory specified: $1" ;;
    esac
  else
    error "Bad src directory specified: $1"
  fi
else
  savedir="$PWD"
  srcdir="$PWD"
fi

if [ "$MSYSTEM" != "MSYS" ]
then
  echo "You must be in an MSYS shell to use this script"
  exit 1
fi

if [ -n "$unpack" ] ; then
  case "$unpack" in
  tbz ) inform "unpacking $1" ; tar xjf $1 ;;
  tgz ) inform "unpacking $1" ; tar xzf $1 ;;
  zip ) inform "unpacking $1" ; unzip -q $1 ;;
  tlz ) inform "unpacking $1" ; tar --lzma -xf $1 ;;
  txz ) inform "unpacking $1" ; tar xJf $1 ;;
  * ) error "unknown pack format" ;;
  esac
  if [ -n "${SRCDIR_}" ]; then
    if [ ! -d "${SRCDIR_}" ]; then
      echo "src package $1 does not unpack into assumed srcdir $SRCDIR_"
      exit 1
    fi
    srcdir=`cd ${SRCDIR_} && pwd`
  fi
  if [ ! -d "$srcdir" ]; then
    echo "src package $1 does not unpack into assumed srcdir $srcdir"
    exit 1
  fi

  srcdir=`cd $srcdir; pwd`
  cd ${srcdir}
  chmod -R u+w *
  if (( $VERPATCH != 0 ))
  then
    let -i patchcnt=1
    while (( $patchcnt <= $VERPATCH ))
    do
      case ${#patchcnt} in
      1) patchnam=bash${VERMAJOR}${VERMINOR}-00${patchcnt} ;;
      2) patchnam=bash${VERMAJOR}${VERMINOR}-0${patchcnt} ;;
      3) patchnam=bash${VERMAJOR}${VERMINOR}-${patchcnt} ;;
      *) error "Too many patches: $VERPATCH"
      esac
      specific_patchlevel=0 do_patch ${savedir}/${patchnam}
      patchcnt=$(($patchcnt + 1))
    done
  fi
  specific_patchlevel=2 do_patch ${savedir}/01-bash-3.1-msys.patch
  specific_patchlevel=5 do_patch ${savedir}/02-Don-t-load-user32.dll-for-every-shell-process.patch
  specific_patchlevel=2 do_patch ${savedir}/03-bash-3.1-redir-fix-msys.patch
  cd ${savedir}
fi

abovedir=`cd ${srcdir}/..; pwd`
PREFIX=/usr
opt_flags="-O2 -fno-unit-at-a-time -s -march=i386 -mtune=i686"
export CFLAGS=${CFLAGS:-"${opt_flags}"}
export CPPFLAGS="${CPPFLAGS}"
export CXXFLAGS=${CXXFLAGS:-"${opt_flags}"}
export F77FLAGS=${F77FLAGS:-"${opt_flags}"}
export GCJFLAGS=${GCJFLAGS:-"${opt_flags}"}
export LDFLAGS="${LDFLAGS} -Wl,--enable-auto-import"
export LIBS="-lregex"

# NO SPACES!!
export PATH=`pwd`:/bin:/usr/local/bin:/mingw/bin:/c/WINDOWS/system32:/c/WINDOWS

mkdir -p ${abovedir}/_build
builddir=${abovedir}/_build
mkdir -p ${abovedir}/_inst
instdir=${abovedir}/_inst
cd ${builddir}

msys_build_deps() {

  local build_deps="
    msys-gcc-bin
    msys-autoconf-bin
    msys-bison-bin
    msys-bison-rtm
    msys-core-ext
    msys-make-bin
    msys-file-bin
    msys-patch-bin
    msys-libtermcap-dev
    msys-libregex-dev
  "
  
  mingw-get install $build_deps
}

msys_conf_prep() {
  inform "Preparing ${PKG}"
  cd ${srcdir}
  autoconf --force
  # Force usage of generated y.tab.c
  rm -f y.tab.c y.tab.h
  cd ${builddir}
}

msys_conf () {
  confargs="--prefix=${PREFIX} \
	--datarootdir=\${prefix}/share --docdir=\${prefix}/${RELDOCDIR}
	--sbindir=\${prefix}/sbin --libexecdir=\${prefix}/sbin \
	--sysconfdir=/etc --localstatedir=/var \
	--disable-nls --disable-rpath --without-curses"

  ${srcdir}/configure --srcdir=${srcdir} ${confargs} \
	CFLAGS="${CFLAGS}" \
	CPPFLAGS="${CPPFLAGS}" \
	CXXFLAGS="${CXXFLAGS}" \
	LDFLAGS="${LDFLAGS}" \
	LIBS="${LIBS}"
}

msys_build () {
  inform "Building ${PKG}"
  make
  # must compile y.tab.c at -O0
  rm -f .build
  rm -f y.tab.o
  make CFLAGS="${CFLAGS/ -O? / -O0 }"
}

msys_check () {
  inform "Testing ${PKG}"
  (make -k check 2>&1 || /bin/true) | tee ${builddir}/${PKG}-check.log
}

msys_install () {
  inform "Installing ${PKG}"
  cp ${srcdir}/lib/readline/doc/rluser.texi ${srcdir}/doc
  cp ${srcdir}/lib/readline/doc/hsuser.texi ${srcdir}/doc
  make install DESTDIR=${instdir}

  verbose cp -p ${instdir}${PREFIX}/bin/bash.exe ${instdir}${PREFIX}/bin/sh.exe
  verbose mkdir -p ${instdir}${PREFIX}/${RELDOCDIR}
  verbose cp -p ${srcdir}/CHANGES \
	${srcdir}/AUTHORS \
	${srcdir}/COMPAT \
	${srcdir}/COPYING \
	${srcdir}/NEWS \
	${srcdir}/NOTES \
	${srcdir}/POSIX \
	${srcdir}/RBASH \
	${srcdir}/README \
	${srcdir}/doc/FAQ \
	${srcdir}/doc/INTRO \
	${srcdir}/doc/article.ps ${instdir}${PREFIX}/${RELDOCDIR}

  verbose rm -f ${instdir}${PREFIX}/share/info/dir

  echo '.so man1/bash.1' > ${instdir}${PREFIX}/share/man/man1/sh.1
  echo '.so man1/bash_builtins.1' > ${instdir}${PREFIX}/share/man/man1/alias.1
  for f in bg bind break builtin caller case cd command compgen complete \
     continue declare dirs disown do done elif else enable esac eval exec \
     exit export fc fg fi for function getopts hash help history if in jobs \
     let local logout popd pushd read readonly return select set shift shopt \
     source suspend then time times trap type typeset ulimit umask unalias \
     unset until wait while ; do
    echo '.so man1/bash_builtins.1' > ${instdir}${PREFIX}/share/man/man1/$f.1
  done


  verbose /usr/bin/install -d -m 755 ${instdir}${PREFIX}/share/doc/MSYS
  verbose /usr/bin/install -m 644 ${abovedir}/msys-bash.RELEASE_NOTES \
	${instdir}${PREFIX}/share/doc/MSYS/${PKG}-${VER}-${BLD}-${SYS}.RELEASE_NOTES.txt
}

msys_package () {
  inform "Packaging ${PKG}"
  cd ${instdir}${PREFIX}

  set_cmparg "${BINPKG}"
  tar cv${cmparg} --hard-dereference -f ${abovedir}/${BINPKG} ${BIN_CONTENTS}

  set_cmparg "${LICPKG}"
  tar cv${cmparg} --hard-dereference -f ${abovedir}/${LICPKG} ${LIC_CONTENTS}

  set_cmparg "${DOCPKG}"
  tar cv${cmparg} --hard-dereference -f ${abovedir}/${DOCPKG} ${DOC_CONTENTS}


  cd ${abovedir}
  set_cmparg "${SRCPKG}"
  tar cv${cmparg} -f ./${SRCPKG} \
    ${PKG}-${VERMAJOR}.${VERMINOR}.tar.gz \
    bash31-??? \
    01-bash-3.1-msys.patch \
    02-Don-t-load-user32.dll-for-every-shell-process.patch \
    03-bash-3.1-redir-fix-msys.patch \
    msys-bash.RELEASE_NOTES \
    msys-build-bash
}

# msys_build_deps
msys_conf_prep
msys_conf
msys_build
### msys_check
msys_install
msys_package

cd "$savedir"

